HEADERS += \
    $$PWD/simpleGUI/drawingwindow.h \
    $$PWD/simpleGUI/intrudedetectconfigurewindow.h \
    $$PWD/simpleGUI/intrudedetectcontrolwindow.h \
    $$PWD/simpleGUI/leavedetectconfigurewindow.h \
    $$PWD/simpleGUI/leavedetectcontrolwindow.h \
    $$PWD/simpleGUI/vehicleconverseconfigurewindow.h \
    $$PWD/simpleGUI/vehicleconversecontrolwindow.h \
    $$PWD/simpleGUI/vehiclecountingconfigurewindow.h \
    $$PWD/simpleGUI/vehiclecountingcontrolwindow.h \
    $$PWD/mainGUI/expand/customanimation.h \
    $$PWD/mainGUI/expand/customtabstyle.h \
    $$PWD/mainGUI/expand/dplayerset.h \
    $$PWD/mainGUI/expand/editablelabel.h \
    $$PWD/mainGUI/expand/myhelper.h \
    $$PWD/mainGUI/expand/scrolltext.h \
    $$PWD/mainGUI/expand/Slider.h \
    $$PWD/mainGUI/expand/wexpand.h \
    $$PWD/mainGUI/expand/wnavigation.h \
    $$PWD/mainGUI/windows/ftoolbtn.h \
    $$PWD/mainGUI/windows/searchbtn.h \
    $$PWD/mainGUI/windows/wareatree.h \
    $$PWD/mainGUI/windows/wdevicemanager.h \
    $$PWD/mainGUI/windows/weventsearch.h \
    $$PWD/mainGUI/windows/wmainpreview.h \
    $$PWD/mainGUI/windows/wplaywindow.h \
    $$PWD/mainGUI/windows/wserver.h \
    $$PWD/mainGUI/windows/wshowinfodetail.h \
    $$PWD/mainGUI/windows/wtitletableview.h \
    $$PWD/mainGUI/QtAwesome/QtAwesome.h \
    $$PWD/mainGUI/QtAwesome/QtAwesomeAnim.h \
    $$PWD/mainGUI/localResource/wlocalresource.h \
    $$PWD/mainGUI/expand/videoplayer.h \
    $$PWD/mainGUI/mainwidget.h \
    $$PWD/mainGUI/vehicleconversewidget.h \
    $$PWD/mainGUI/localResource/vehicleconverseparse.h \
    $$PWD/mainGUI/localResource/vehicleconverseconfig.h \
    $$PWD/mainGUI/localResource/leaveconfig.h \
    $$PWD/mainGUI/localResource/leaveparse.h \
    $$PWD/mainGUI/leavewidget.h

SOURCES += \
    $$PWD/simpleGUI/drawingwindow.cpp \
    $$PWD/simpleGUI/intrudedetectconfigurewindow.cpp \
    $$PWD/simpleGUI/intrudedetectcontrolwindow.cpp \
    $$PWD/simpleGUI/leavedetectconfigurewindow.cpp \
    $$PWD/simpleGUI/leavedetectcontrolwindow.cpp \
    $$PWD/simpleGUI/vehicleconverseconfigurewindow.cpp \
    $$PWD/simpleGUI/vehicleconversecontrolwindow.cpp \
    $$PWD/simpleGUI/vehiclecountingconfigurewindow.cpp \
    $$PWD/simpleGUI/vehiclecountingcontrolwindow.cpp \
    $$PWD/mainGUI/expand/customanimation.cpp \
    $$PWD/mainGUI/expand/dplayerset.cpp \
    $$PWD/mainGUI/expand/editablelabel.cpp \
    $$PWD/mainGUI/expand/myhelper.cpp \
    $$PWD/mainGUI/expand/scrolltext.cpp \
    $$PWD/mainGUI/expand/Slider.cpp \
    $$PWD/mainGUI/expand/wexpand.cpp \
    $$PWD/mainGUI/expand/wnavigation.cpp \
    $$PWD/mainGUI/windows/ftoolbtn.cpp \
    $$PWD/mainGUI/windows/searchbtn.cpp \
    $$PWD/mainGUI/windows/wareatree.cpp \
    $$PWD/mainGUI/windows/wdevicemanager.cpp \
    $$PWD/mainGUI/windows/weventsearch.cpp \
    $$PWD/mainGUI/windows/wmainpreview.cpp \
    $$PWD/mainGUI/windows/wplaywindow.cpp \
    $$PWD/mainGUI/windows/wserver.cpp \
    $$PWD/mainGUI/windows/wshowinfodetail.cpp \
    $$PWD/mainGUI/windows/wtitletableview.cpp \
    $$PWD/mainGUI/QtAwesome/QtAwesome.cpp \
    $$PWD/mainGUI/QtAwesome/QtAwesomeAnim.cpp \
    $$PWD/mainGUI/localResource/wlocalresource.cpp \
    $$PWD/mainGUI/expand/videoplayer.cpp \
    $$PWD/mainGUI/mainwidget.cpp \
    $$PWD/mainGUI/vehicleconversewidget.cpp \
    $$PWD/mainGUI/localResource/vehicleconverseparse.cpp \
    $$PWD/mainGUI/localResource/vehicleconverseconfig.cpp \
    $$PWD/mainGUI/localResource/leaveconfig.cpp \
    $$PWD/mainGUI/localResource/leaveparse.cpp \
    $$PWD/mainGUI/leavewidget.cpp

