HEADERS += \
    $$PWD/utils/utility.h \
    $$PWD/segmentation/efficientGraphBased/disjoint_set.h \
    $$PWD/segmentation/efficientGraphBased/segment_graph.h \
    $$PWD/segmentation/efficientGraphBased/segment_image.h \
    $$PWD/acsaliency.h \
    $$PWD/ftsaliency.h \
    $$PWD/hcsaliency.h \
    $$PWD/ittisaliency.h \
    $$PWD/lcsaliency.h \
    $$PWD/mssaliency.h \
    $$PWD/rcsaliency.h \
    $$PWD/srsaliency.h \
    $$PWD/isaliency.h \
    $$PWD/mbsaliency.h \
    $$PWD/GeodesicSaliency/BGMapExtractor_Grid.h \
    $$PWD/GeodesicSaliency/geodesicsaliency.h \
    $$PWD/bmsaliency.h \
    $$PWD/GMRsaliency.h \
    $$PWD/SFSaliency/filter/filter.h \
    $$PWD/SFSaliency/filter/permutohedral.h \
    $$PWD/SFSaliency/superpixel/superpixel.h \
    $$PWD/SFSaliency/utility/fastmath.h \
    $$PWD/SFSaliency/utility/sse_defs.h \
    $$PWD/SFSaliency/sfsaliency.h \
    $$PWD/GCSaliency/cluster/apcluster.h \
    $$PWD/GCSaliency/cluster/CmAPCluster.h \
    $$PWD/GCSaliency/cluster/colorquantize.h \
    $$PWD/GCSaliency/cluster/gmm.h \
    $$PWD/GCSaliency/gcsaliency.h \
    $$PWD/GCSaliency/utility.h

SOURCES += \
    $$PWD/utils/utility.cpp \
    $$PWD/segmentation/efficientGraphBased/segment_image.cpp \
    $$PWD/acsaliency.cpp \
    $$PWD/ftsaliency.cpp \
    $$PWD/hcsaliency.cpp \
    $$PWD/ittisaliency.cpp \
    $$PWD/lcsaliency.cpp \
    $$PWD/mssaliency.cpp \
    $$PWD/rcsaliency.cpp \
    $$PWD/srsaliency.cpp \
    $$PWD/isaliency.cpp \
    $$PWD/mbsaliency.cpp \
    $$PWD/GeodesicSaliency/BGMapExtractor_Grid.cpp \
    $$PWD/GeodesicSaliency/geodesicsaliency.cpp \
    $$PWD/bmsaliency.cpp \
    $$PWD/GMRsaliency.cpp \
    $$PWD/SFSaliency/filter/filter.cpp \
    $$PWD/SFSaliency/filter/permutohedral.cpp \
    $$PWD/SFSaliency/superpixel/superpixel.cpp \
    $$PWD/SFSaliency/sfsaliency.cpp \
    $$PWD/GCSaliency/cluster/apcluster.cpp \
    $$PWD/GCSaliency/cluster/CmAPCluster.cpp \
    $$PWD/GCSaliency/cluster/colorquantize.cpp \
    $$PWD/GCSaliency/cluster/gmm.cpp \
    $$PWD/GCSaliency/gcsaliency.cpp \
    $$PWD/testsaliency.cpp
